trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: ca48ba2a-d46b-44e7-919d-698613e6718c
  imageRepository: azure-vote-front
  containerRegistry: testkuberegistry.azurecr.io
  dockerfilePath: '**/Dockerfile'
  tag: v1

  # Kubernetes Namespace
  k8sNamespace: 'test'
  imagePullSecret: 'secret/acr-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: $(vmImageName)
    #environment: 'shashankbarsinpipelinesjavascriptdocker.aksnamespace'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: $(k8sNamespace)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(k8sNamespace)
              manifests: |
                $(Pipeline.Workspace)/azure-vote-all-in-one-redis.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
